title = "default"
size = [4, 3]
reward = -0.04
gamma = 1
epsilon = 0
probability = [0.8, 0.1, 0.1, 0.0]

[[state]]
    s_type = "S"
    position = [0, 0]

[[state]]
    s_type = "T"
    position = [3, 2]
    value = 1

[[state]]
    s_type = "T"
    position = [3, 1]
    value = -1

[[state]]
    s_type = "F"
    position = [1, 1]

