title = "world2"
size = [4, 3]
reward = -0.04
gamma = 1
epsilon = 0
probability = [0.8, 0.1, 0.1, 0.0]


[[state]]
    s_type = "S"
    position = [1, 2]

[[state]]
    s_type = "T"
    position = [4, 2]
    value = -1

[[state]]
    s_type = "F"
    position = [2, 2]

[[state]]
    s_type = "F"
    position = [3, 2]

[[state]]
    s_type = "B"
    position = [3, 1]
    value = 50

[[state]]
    s_type = "B"
    position = [3, 3]
    value = -50

