title = "world3"
size = [5, 5]
reward = -0.04
gamma = 1
epsilon = 0
probability = [0.8, 0.1, 0.1, 0.0]

[[state]]
    s_type = "S"
    position = [3, 3]

[[state]]
    s_type = "T"
    position = [1, 1]
    value = -1

[[state]]
    s_type = "T"
    position = [1, 5]
    value = 1

[[state]]
    s_type = "T"
    position = [5, 1]
    value = 1

[[state]]
    s_type = "T"
    position = [5, 5]
    value = -1

[[state]]
    s_type = "F"
    position = [2, 2]

[[state]]
    s_type = "F"
    position = [4, 2]

[[state]]
    s_type = "F"
    position = [2, 4]

[[state]]
    s_type = "F"
    position = [4, 4]

[[state]]
    s_type = "S"
    position = [3, 1]
    value = 50

[[state]]
    s_type = "S"
    position = [1, 3]
    value = -50

[[state]]
    s_type = "S"
    position = [5, 3]
    value = -50

[[state]]
    s_type = "S"
    position = [3, 5]
    value = 50
